remote_theme: MicrosoftLearning/Jekyll-Theme
title: 'MD-102: Microsoft 365 Endpoint Administrator'
exclude:
  - readme.md
  - .github/
  - tools/
header_pages:
  - index.html
author: Microsoft Learning
twitter_username: mslearning
github_username:  MicrosoftLearning
plugins:
  - jekyll-sitemap
  - jekyll-mentions
  - jemoji
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    disable: true
# Lab guides and the getting-started page use the course layout.
defaults:
  - scope:
      path: "Instructions/Labs"
    values:
      layout: lab
